# Generated by Django 2.2.7 on 2020-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='submission',
            name='post',
        ),
        migrations.AddField(
            model_name='submission',
            name='post',
            field=models.ManyToManyField(to='main.Post'),
        ),
    ]
