# Generated by Django 2.2.7 on 2020-02-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200206_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Teacher'),
        ),
    ]
