# Generated by Django 2.2.7 on 2020-02-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_submission_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='post',
            field=models.ManyToManyField(null=True, to='main.Post'),
        ),
    ]
